apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
spec:
  type: {{ .Values.ingress.ServiceType }}
  ports:
  - port: 8080
  selector:
    app: {{ .Release.Name }}

    